cs251project/django/feedr/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedr'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^home/*', views.adminHome_view, name='adminHome'), #Check this one out
    url(r'^admin/add/$', views.addCourses_view, name='addCourses'),
    url(r'^admin/manage/$', views.manageCourses_view, name='manageCourses'),
    url(r'^admin/courses/$', views.courses_view, name='courses'),
    url(r'^admin/feedbacks/$', views.feedback_view, name='feedbacks'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', views.sign_up_view, name='signup'),
    url(r'^home/$', views.home_view, name='home'), #Check this one out
    url(r'^enroll/$', views.enroll_view, name='enroll'),
    url(r'^validateStudent/$', views.valid_view, name='valid'),
    url(r'^getFeedbacks/$', views.get_feedbacks_view, name='getFeedbacks'),
    url(r'^getDeadlines/$', views.get_deadlines_view, name='getDeadlines'),
    url(r'^viewDeadlines/$', views.viewDeadlines_view, name='viewDeadlines'),
    url(r'^addDeadlines/$', views.addDeadlines_view, name='addDeadlines'),
    url(r'^responses/$', views.responses_view, name='responses'),
    url(r'^addFeedback/$', views.addFeedback_view, name='addFeedback'),
    url(r'^addQuestion/$', views.addQuestions_view, name='addQuestions'),
    url(r'^Googlelogin/$', views.Googlelogin_view, name='Googlelogin'),
]

cs251project/django/group22/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^feedr/', include('feedr.urls')),
    url(r'^admin/', admin.site.urls),
]

cs251project/django/feedr/models.py
from django.db import models

class StudentDetails(models.Model):
    name = models.CharField(max_length=100)
    roll_number = models.BigIntegerField(primary_key=True)
    password = models.CharField(max_length=100)
    cpi = models.DecimalField(max_digits=5,decimal_places=2)
    def __str__(self):
        return self.name

class Courses(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, primary_key=True)
    students = models.ManyToManyField(StudentDetails)
    def __str__(self):
        return self.code

class Assignments(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Courses)
    deadline = models.DateTimeField(['%Y-%m-%d %H:%M:%S',])
    def __str__(self):
        return self.name

class Feedbacks(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Courses)
    deadline = models.DateTimeField(['%Y-%m-%d %H:%M:%S',])
    def __str__(self):
        return self.name

class Questions(models.Model):
    question = models.CharField(max_length=200)
    ques_type = models.CharField(max_length=100)
    feedback = models.ForeignKey(Feedbacks)
    def __str__(self):
        return self.question

class Answer(models.Model):
    answer = models.CharField(max_length=200)
    ques = models.ForeignKey(Questions)
    def __str__(self):
        return self.answer

cs251project/django/feedr/forms.py
from django import forms
import datetime
from .models import *

class DeadlineForm(forms.Form):
    courseCode = forms.ModelChoiceField(empty_label="Select a Course" ,queryset=Courses.objects.all())
    assignName = forms.CharField()
    deadlineDate = forms.DateTimeField(['%d-%m-%Y %H:%M:%S',])

class SignUpForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(min_length=4,widget=forms.PasswordInput)
    pwd2 = forms.CharField(min_length=4,widget=forms.PasswordInput)

class CourseDetailForm (forms.Form):
    courseCode = forms.CharField()
    courseName = forms.CharField()
    midSem = forms.DateField(['%d-%m-%Y'])
    endSem = forms.DateField(['%d-%m-%Y'])

class QuestionForm (forms.Form):
    question = forms.CharField()
    ques_type = forms.ChoiceField(widget=forms.RadioSelect, choices=(('Character Field','Textual question'),('Radio Button','Ratings(1 to 5)')))

class EnrollmentForm (forms.Form):
    current_course = forms.CharField()
    students = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=StudentDetails.objects.all())

cs251project/django/feedr/views.py
import datetime
import os
import collections
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, HttpRequest
from django.urls import reverse
from django.core.exceptions import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib.auth.decorators import user_passes_test
from .forms import *
from.models import *
from apiclient import discovery
from apiclient.discovery import build
import httplib2
import csv
import json
from oauth2client import client
from django.views.decorators.csrf import csrf_exempt
from django.utils.encoding import force_text
from django.core.serializers.json import DjangoJSONEncoder
from django.core.serializers import serialize

# Create your views here.
PATH = os.path.dirname(os.path.realpath(__file__))
#@csrf_protect
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if not User.objects.filter(username="admin"):
        with open(PATH+'/admin_details.csv', 'r') as csvfile:
            spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
            for row in spamreader:
                u1=User.objects.create_user(username=row[0],password=row[1],email=row[2])
    if request.user is not None:
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('feedr:home'))
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pwd']
        user = authenticate(username=username, password=password)
        if user is not None:
            if username == "admin" and password == "admin":
                login(request, user)
                return HttpResponseRedirect(reverse('feedr:adminHome'))
            login(request, user)
            return HttpResponseRedirect(reverse('feedr:home'))
        else:
            msg = "Invalid Credentials"
            return render(request, 'feedr/login.html', {'error_message': msg,'path':PATH})
    else:
        return render(request, 'feedr/login.html',{'path':PATH})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('feedr:login'))

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def home_view(request):
    return render(request, 'feedr/home.html', {'activeStatus':["active","","","",""],'path':PATH})

def sign_up_view(request):
    if request.method == 'POST':
        form=SignUpForm(request.POST)
        error=""
        if form.is_valid():
            final=form.cleaned_data
            try:
            	User.objects.get(username=final['username'])
            	error="Username already exists"
            	data={'username':final['username'],'email':final['email']}
            	form=SignUpForm(initial=data)
            	return render(request,'feedr/signup.html',{'path':PATH,'form':form,'uerror':error})
            except:
            	if final['pwd2']!=final['password']:
            		error="Passwords do not match"
            		return render(request,'feedr/signup.html',{'path':PATH,'form':form,'uerror':error})
            	user = User.objects.create_user(username=final['username'], email=final['email'], password=final['password'])
            	login(request, user)
            return HttpResponseRedirect(reverse('feedr:home'))
        else:
        	#print form.errors
    	    return render(request, 'feedr/signup.html',{'path':PATH,'form':form})    	
    form = SignUpForm(initial={'username':"",'email':""})
    return render(request, 'feedr/signup.html',{'path':PATH,'form':form})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def addDeadlines_view(request):
    if request.method=='POST':
        form=DeadlineForm(request.POST)
        if form.is_valid():
            final=form.cleaned_data
            sub_date=Assignments(name=final['assignName'],course=final['courseCode'],deadline=final['deadlineDate'])
            sub_date.save()
            return HttpResponseRedirect(reverse('feedr:home'))
        return render(request,'feedr/addDeadlines.html/',{'activeStatus':["","","active","",""],'path':PATH,'form':form})    
    form=DeadlineForm()
    return render(request,'feedr/addDeadlines.html/',{'activeStatus':["","","active","",""],'path':PATH,'form':form})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def viewDeadlines_view(request):
    courseList = Courses.objects.all()
    deadlineList=[]
    name=["Running Deadlines","Running Feedbacks","Finished Deadlines","Finished Feedbaks"]
    if request.method=='POST' and request.POST['course']!="All":
        crs=Courses.objects.get(code=request.POST['course'])
        deadlineList.append(Assignments.objects.filter(course=crs,deadline__gte=datetime.date.today()).order_by("-deadline"))
        deadlineList.append(Feedbacks.objects.filter(course=crs,deadline__gte=datetime.date.today()).order_by("-deadline"))
        deadlineList.append(Assignments.objects.filter(course=crs,deadline__lte=datetime.date.today()).order_by("-deadline"))
        deadlineList.append(Feedbacks.objects.filter(course=crs,deadline__lte=datetime.date.today()).order_by("-deadline"))
        return render(request,'feedr/viewDeadlines.html',{'course':crs.code,'activeStatus':["","","","","active"],'deadlineList':deadlineList,'courseList':courseList,'name':name,'path':PATH})        
    deadlineList.append(Assignments.objects.filter(deadline__gte=datetime.date.today()).order_by("-deadline"))
    deadlineList.append(Assignments.objects.exclude(deadline__gte=datetime.date.today()).order_by("-deadline"))
    return render(request,'feedr/viewDeadlines.html',{'activeStatus':["","","","","active"],'deadlineList':deadlineList,'courseList':courseList,'name':name,'path':PATH})

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def addFeedback_view(request):    
    form=DeadlineForm()
    return render(request,'feedr/addFeedback.html/',{'activeStatus':["","active","","",""],'path':PATH,'form':form})    

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def addQuestions_view(request):
    if request.method=='POST' and 'Feedback' in request.POST:
        form=DeadlineForm(request.POST)
        if form.is_valid():
            final=form.cleaned_data
            fb1=Feedbacks(name=final['assignName'],course=final['courseCode'],deadline=final['deadlineDate'])
            fb1.save()
            form = QuestionForm()
            return render(request,'feedr/addQuestions.html/',{'activeStatus':["","active","","",""],'path':PATH,'form':form,'current_feedback':fb1})
        return render(request,'feedr/addFeedback.html/',{'activeStatus':["","active","","",""],'path':PATH,'form':form})    
    elif request.method=='POST':
        form=QuestionForm(request.POST)
        if form.is_valid():
            final = form.cleaned_data
            fb1 = Feedbacks.objects.filter(name=request.POST['feedback'],course=Courses.objects.get(code=request.POST['course']))[0]
            ques = Questions(question=final['question'],ques_type=final['ques_type'],feedback=fb1)
            ques.save()
            if 'button1' in request.POST:
                questions = Questions.objects.filter(feedback=fb1)
                form = QuestionForm()
                return render(request,'feedr/addQuestions.html/',{'activeStatus':["","active","","",""],'path':PATH,'form':form,'current_feedback':fb1,'questions':questions}) 
            elif 'button2' in request.POST:
                return HttpResponseRedirect(reverse('feedr:home'))
    return HttpResponseRedirect(reverse('feedr:home'))

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def responses_view(request):
    crs = Courses.objects.all()
    if request.method == 'POST' and 'Feedback' in request.POST:
        feedbacks = Feedbacks.objects.filter(course=Courses.objects.get(code=request.POST['course']))
        questions = Questions.objects.filter(feedback=Feedbacks.objects.filter(course=Courses.objects.get(code=request.POST['course']),name=request.POST['Feedback'])[0])
        responses = {}
        for q in questions:
            res = Answer.objects.filter(ques=q)
            if q.ques_type == "Character Field":
                responses[q]=res
            else:
                resp = {'1':0,'2':0,'3':0,'4':0,'5':0}
                for r in res:
                    resp[r.answer] = resp[r.answer]+1
                res = collections.OrderedDict(sorted(resp.items()))
                responses[q]=res
        return render(request,'feedr/viewResponses.html',{'path':PATH,'activeStatus':["","","","active",""],'courselist':crs,'feedbacklist':feedbacks,'questionlist':questions,'responselist':responses,'course':request.POST['course'],'Feedback':request.POST['Feedback']})
    elif request.method == 'POST':
        feedbacks = Feedbacks.objects.filter(course=Courses.objects.get(code=request.POST['course']))
        return render(request,'feedr/viewResponses.html',{'path':PATH,'activeStatus':["","","","active",""],'courselist':crs,'feedbacklist':feedbacks,'course':request.POST['course']})
    else:
        return render(request,'feedr/viewResponses.html',{'path':PATH,'activeStatus':["","","","active",""],'courselist':crs})

#Admin part (more or less)
def admincheck(user):
    return (user.username == 'admin')

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def adminHome_view(request):
    courseList = Courses.objects.all()
    enroll = False
    if not StudentDetails.objects.all():

cs251project/django/feedr/templates/feedr/addCourses.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Courses</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Add a New Course</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
 {% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Course Code : </label>
      <div class="col-sm-6">
        {{form.courseCode}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Course Name : </label>
      <div class="col-sm-6">
        {{form.courseName}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">MidSemester Date (dd-mm-yyyy) : </label>
      <div class="col-sm-6">
        {{form.midSem}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">EndSemester Date (dd-mm-yyyy) : </label>
      <div class="col-sm-6">
        {{form.endSem}}
      </div>
    </div>
<input type="submit" value="Submit">
</form>

</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/addDeadlines.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Deadlines</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
    {% load i18n %}
    <script type="text/javascript" src="/my_admin/jsi18n/"></script>
<script type="text/javascript" src="/media/admin/js/core.js"></script>
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Set a Deadline</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Course Code : </label>
      <div class="col-sm-6">
        {{form.courseCode}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Assignment Name : </label>
      <div class="col-sm-6">
        {{form.assignName}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">Deadline Date (dd-mm-yyyy h:m:s) : </label>
      <div class="col-sm-6">
        {{form.deadlineDate}}
      </div>
    </div>
<input type="submit" value="Submit">
</form>

</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/addFeedback.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Deadlines</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Add a feedback</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
<form action="{% url 'feedr:addQuestions' %}" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Course Code : </label>
      <div class="col-sm-6">
        {{form.courseCode}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Feedback Name : </label>
      <div class="col-sm-6">
        {{form.assignName}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">Deadline Date (dd-mm-yyyy h:m:s) : </label>
      <div class="col-sm-6">
        {{form.deadlineDate}}
      </div>
    </div>
<center><input type="submit" name="Feedback" value="Add questions"></center>
</form>

</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/addQuestions.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Deadlines</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Add a question</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Question : </label>
      <div class="col-sm-6">
        {{form.question}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Question type : </label>
      <div class="col-sm-6">
        {{form.ques_type}}
      </div>
    </div>
    <input type="hidden" name="feedback" value="{{ current_feedback }}" />
    <input type="hidden" name="course" value="{{ current_feedback.course.code }}" />
<center><input type="submit" name="button1" value="Add another question"><input type="submit" name="button2" value="Make Form"></center>
</form>
{% if questions %}
  <h4><u>Entered questions:</u> </h4>
<table class="table table-striped">
  <tbody>
    {% for q in questions %}
    <tr>
        <td>{{q.question}}</td>
        <td>{{q.ques_type}}</td>
    </tr>
    {% endfor  %}
  </tbody>
</table>
{% endif %}
</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/course.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>

{% if courseList %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for cr in courseList %}
        <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="course" value="{{ cr.code }}">{{cr.code}}</button>
    {% endfor  %}
    </form>
    <p><h4><u>Course Name:</u> </h4> {{current_course.name}}</p>
    <p><h4><u>Course Code:</u> </h4> {{current_course.code}}</p>
	</ul>
	</div>
<h4><u>Deadlines:</u> </h4>
<table class="table table-striped">
  <thead>
    <tr>
    {% for dl in current_course.assignments_set.all %}
        <th>{{dl.name}}</th>
    {% endfor  %}
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for dl in current_course.assignments_set.all %}
        <td>{{dl.deadline}}</td>
    {% endfor  %}
    </tr>
  </tbody>
</table>
<h4><u>Feedbacks:</u> </h4>
<table class="table table-striped">
  <thead>
    <tr>
    {% for fb in current_course.feedbacks_set.all %}
        <form class="form-horizontal" action="{% url 'feedr:feedbacks' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="feedback" value="{{fb}}">{{fb.name}}</button>
        </form>
    {% endfor  %}
    </tr>
  </thead>
</table>
<h4><u>Students:</u> </h4>
<table class="table table-striped">
  <tbody>
    {% for st in current_course.students.all %}
    <tr>
        <td>{{st.name}}</td>
        <td>{{st.roll_number}}</td>
        {% for cr in st.courses_set.all %}
        <td>{{cr.name}}</td>
        {% endfor  %}
    </tr>
    {% endfor  %}
  </tbody>
</table>
{% endif %}
</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/feedback.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>

{% if courseList %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for cr in courseList %}
        <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="course" value="{{ cr.code }}">{{cr.code}}</button>
    {% endfor  %}
    </form>
	</ul>
	</div>
    <p><h4><u>Feedback Name:</u> </h4>{{current_feedback.name}}</p>
    <p><h4><u>Feedback Deadline:</u> </h4>{{current_feedback.deadline}}</p>
    <h4><u>Questions:</u> </h4>
<table class="table table-striped">
  <tbody>
    {% for ques in current_feedback.questions_set.all %}
    <tr>
        <td>{{ques.question}}</td>
    </tr>
    {% endfor  %}
  </tbody>
</table>
{% endif %}
</div>
</body>
</html>

cs251project/django/feedr/templates/feedr/home.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>
<br>
<br>
{% if user.username == "admin" %}
	<h5>Click <a href="/feedr/enroll">here</a> to register the students to database from csv file</h5>
{% endif %}
{% if courseList %}
<p>These are the available courses</p>
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for course in courseList %}
    <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-default" name="course" value="{{ course.code }}">{{course.code}}</button>
    {% endfor  %}
	</ul>
	</div>
{% endif %}
</div>
</body>
</html>