lab10/feedr/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedr'
urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^home/$', views.adminHome_view, name='adminHome'),
    url(r'^admin/add/$', views.addCourses_view, name='addCourses'),
    url(r'^admin/manage/$', views.manageCourses_view, name='manageCourses'),
    url(r'^admin/courses/$', views.courses_view, name='courses'),
    url(r'^admin/feedbacks/$', views.feedback_view, name='feedbacks'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', views.sign_up_view, name='signup'),
    url(r'^home/$', views.home_view, name='home'),
    url(r'^enroll/$', views.enroll_view, name='enroll'),
    url(r'^addDeadlines/$', views.addDeadlines_view, name='addDeadlines'),
    url(r'^viewDeadlines/$', views.viewDeadlines_view, name='viewDeadlines'),
    url(r'^validateStudent/$', views.valid_view, name='valid'),
]

lab10/group22/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^feedr/', include('feedr.urls')),
]

lab10/feedr/models.py
from django.db import models

class StudentDetails(models.Model):
    name = models.CharField(max_length=100)
    roll_number = models.BigIntegerField(primary_key=True)
    password = models.CharField(max_length=100)
    cpi = models.DecimalField(max_digits=5,decimal_places=2)
    def __str__(self):
        return self.name

class Courses(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=100, primary_key=True)
    students = models.ManyToManyField(StudentDetails)
    def __str__(self):
        return self.name

class Assignments(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Courses)
    deadline = models.DateTimeField(['%d-%m-%Y %H:%M:%S',])
    def __str__(self):
        return self.name

class Feedbacks(models.Model):
    name = models.CharField(max_length=100)
    course = models.ForeignKey(Courses)
    deadline = models.DateTimeField(['%d-%m-%Y %H:%M:%S',])
    def __str__(self):
        return self.name

class Questions(models.Model):
    question = models.CharField(max_length=200)
    ques_type = models.CharField(max_length=100)
    feedback = models.ForeignKey(Feedbacks)
    def __str__(self):
        return self.question

class Answer(models.Model):
    answer = models.CharField(max_length=200)
    ques = models.ForeignKey(Questions)
    def __str__(self):
        return self.answer

lab10/feedr/forms.py
from django import forms
import datetime
from .models import *

def courseList():
	crs=Courses.objects.all()
	courseList=[]
	i=1
	for course in crs:
		t=(i,(course.code))
		courseList.append(t)
		i=i+1
	return courseList

class SignUpForm(forms.Form):
	username = forms.CharField()
	email = forms.EmailField()
	password = forms.CharField(min_length=4,widget=forms.PasswordInput)
	pwd2 = forms.CharField(min_length=4,widget=forms.PasswordInput)

class DeadlineForm(forms.Form):
    courseCode = forms.ChoiceField(choices=courseList())
    assignName = forms.CharField()
    deadlineDate = forms.DateTimeField(['%d-%m-%Y %H:%M:%S',])

class CourseDetailForm (forms.Form):
    courseCode = forms.CharField()
    courseName = forms.CharField()
    midSem = forms.DateField(['%d-%m-%Y'])
    endSem = forms.DateField(['%d-%m-%Y'])

class EnrollmentForm (forms.Form):
    current_course = forms.CharField()
    students = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=StudentDetails.objects.all())

lab10/feedr/views.py
import datetime
import os
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from .forms import *
from.models import *
from apiclient import discovery
import httplib2
import csv
from oauth2client import client
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
PATH = os.path.dirname(os.path.realpath(__file__))
#@csrf_protect


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if not User.objects.filter(username="admin"):
        with open(PATH+'/admin_details.csv', 'r') as csvfile:
            spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
            for row in spamreader:
                u1=User.objects.create_user(username=row[0],password=row[1],email=row[2])
    if request.user is not None:
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('feedr:home'))
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['pwd']
        user = authenticate(username=username, password=password)
        if user is not None:
            if username == "admin" and password == "admin":
                login(request, user)
                return HttpResponseRedirect(reverse('feedr:adminHome'))
            login(request, user)
            return HttpResponseRedirect(reverse('feedr:home'))
        else:
            msg = "Invalid Credentials"
            return render(request, 'feedr/login.html', {'error_message': msg,'path':PATH})
    else:
        return render(request, 'feedr/login.html',{'path':PATH})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('feedr:login'))

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')


def home_view(request):
    return render(request, 'feedr/home.html', {'activeStatus':["active","","","",""],'path':PATH})


def sign_up_view(request):
    if request.method == 'POST':
        form=SignUpForm(request.POST)
        if form.is_valid():
            final=form.cleaned_data
            user = User.objects.create_user(username=final['username'], email=final['email'], password=final['password'])
            login(request, user)
            return HttpResponseRedirect(reverse('feedr:home'))
    form = SignUpForm()
    print(form.as_table())
    return render(request, 'feedr/signup.html',{'path':PATH,'form':form})


def addDeadlines_view(request):
    if request.method=='POST':
        form=DeadlineForm(request.POST)
        print form.errors
        if form.is_valid():
            print "hello"
            final=form.cleaned_data
            #sub_date=Assignments(name=,course=,deadline=)
            #sub_date.save()
            print final['courseCode']
            return HttpResponseRedirect('http://localhost/feedr/home')
    form=DeadlineForm()
    return render(request,'feedr/addDeadlines.html/',{'activeStatus':["","","active","",""],'form':form,'path':PATH})


def viewDeadlines_view(request):
    deadlineList=[]
    name=["Running Deadilnes","Finished Deadlines"]
    deadlineList.append(Assignments.objects.filter(deadlineDate__gte=datetime.date.today()).order_by("-deadlineDate"))
    deadlineList.append(Assignments.objects.exclude(deadlineDate__gte=datetime.date.today()).order_by("-deadlineDate"))
    return render(request,'feedr/viewDeadlines.html',{'activeStatus':["","","","","active"],'deadlineList':deadlineList,'name':name,'path':PATH})


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def adminHome_view(request):
    courseList = Courses.objects.all()
    enroll = False
    if not StudentDetails.objects.all():
        enroll = True
    return render(request, 'feedr/home.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList, 'enroll':enroll}) 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def courses_view(request):
    courseList = Courses.objects.all()
    if request.method == 'POST':
        crs_name = request.POST['course']
        course = Courses.objects.get(name=crs_name)
        return render(request, 'feedr/course.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList, 'current_course':course}) 
    else:
        return render(request, 'feedr/home.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList}) 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def feedback_view(request):
    courseList = Courses.objects.all()
    if request.method == 'POST':
        fdb_name = request.POST['feedback']
        fdb = Feedbacks.objects.filter(name=fdb_name)[0]
        return render(request, 'feedr/feedback.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList, 'current_feedback':fdb}) 
    else:
        return render(request, 'feedr/home.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList})
    

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def addCourses_view(request):
    if request.method == 'POST':
        form = CourseDetailForm(request.POST)
        if form.is_valid():
            final = form.cleaned_data
            if Courses.objects.filter(code=final['courseCode']):
                msg = "Another Course with same course code already exists!"
                return render(request, 'feedr/addCourses.html', {'activeStatus':["","active",""],'form':form,'path':PATH,'error_message':msg})
            else:
                c1 = Courses(name=final['courseName'],code=final['courseCode'])
                c1.save()
                mid_sem = Assignments(name="MidSemester Exam", course=c1, deadline=final['midSem'])
                end_sem = Assignments(name="EndSemester Exam", course=c1, deadline=final['endSem'])
                mid_sem.save()
                end_sem.save()
                fb1 = Feedbacks(name="Midsem Feedback", course=c1, deadline=final['midSem'])
                fb2 = Feedbacks(name="Endsem Feedback", course=c1, deadline=final['endSem'])
                fb1.save()
                fb2.save()
                for f in [fb1,fb2]:
                    with open(PATH +'/questions.csv', 'r') as csvfile:
                        spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
                        for row in spamreader:
                            q1=Questions(question=row[0],ques_type=row[1],feedback=f)
                            q1.save()
                return HttpResponseRedirect(reverse('feedr:home'))
        return render(request, 'feedr/addCourses.html', {'activeStatus':["","active",""],'form':form,'path':PATH}) 
    form = CourseDetailForm()
    return render(request, 'feedr/addCourses.html', {'activeStatus':["","active",""],'form':form,'path':PATH}) 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def manageCourses_view(request):
    courseList = Courses.objects.all()
    if request.method == 'POST':
        if 'course' in request.POST:
            c1 = Courses.objects.get(name=request.POST['course']) 
            form = EnrollmentForm()
            form.fields["students"].queryset = StudentDetails.objects.all().exclude(courses=c1)
            return render(request, 'feedr/manageCourses.html', {'activeStatus':["","","active"], 'courseList':courseList, 'form':form, 'path':PATH, 'current_course':c1})
        else:
            form = EnrollmentForm(request.POST)
            if form.is_valid():
                final = form.cleaned_data
                c1 = Courses.objects.get(name=final['current_course']) 
                for st in final['students']:
                    c1.students.add(st)
                c1.save()
                return HttpResponseRedirect(reverse('feedr:home'))
            else:
                return HttpResponseRedirect(reverse('feedr:home'))
    return render(request, 'feedr/manageCourses.html', {'activeStatus':["","","active"],'courseList':courseList, 'path':PATH}) 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
@login_required(login_url='/feedr/login/')
def enroll_view(request):
    with open(PATH+'/student_details.csv', 'r') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in spamreader:
            s1=StudentDetails(name=row[0],roll_number=int(row[1]),password=row[2],cpi=float(row[3]))
            s1.save()
    courseList = Courses.objects.all()
    return render(request, 'feedr/home.html', {'activeStatus':["active","",""],'path':PATH,'courseList':courseList, 'enroll':False})


#Android Related Parts
@csrf_exempt
def valid_view(request):
    if request.method=='POST':
        try:
            list_of_studs = StudentDetails.objects.filter(roll_number=int(request.POST['username']))
        except:
            return HttpResponse("Invalid")
        if list_of_studs:
            if list_of_studs[0].password==request.POST['password']:
                return HttpResponse("Welcome "+list_of_studs[0].name)
            else:
                print ("wrong pwd")
    return HttpResponse("Invalid")

lab10/feedr/templates/feedr/addCourses.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Courses</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Add a New Course</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
 {% if error_message %}<p style="color:red"><strong>{{ error_message }}</strong></p>{% endif %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Course Code : </label>
      <div class="col-sm-6">
        {{form.courseCode}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Course Name : </label>
      <div class="col-sm-6">
        {{form.courseName}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">MidSemester Date (dd-mm-yyyy) : </label>
      <div class="col-sm-6">
        {{form.midSem}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">EndSemester Date (dd-mm-yyyy) : </label>
      <div class="col-sm-6">
        {{form.endSem}}
      </div>
    </div>
<input type="submit" value="Submit">
</form>

</div>
</body>
</html>

lab10/feedr/templates/feedr/addDeadlines.html
<!DOCTYPE html>
<html>
<head>
	<title>Add Deadlines</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}

<h4>Set a Deadline</h4>

 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_courseCode">Course Code : </label>
      <div class="col-sm-6">
        {{form.courseCode}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_assignName">Assignment Name : </label>
      <div class="col-sm-6">
        {{form.assignName}}
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_deadlineDate">Deadline Date (dd-mm-yyyy h:m:s) : </label>
      <div class="col-sm-6">
        {{form.deadlineDate}}
      </div>
    </div>
<input type="submit" value="Submit">
</form>

</div>
</body>
</html>

lab10/feedr/templates/feedr/course.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>

{% if courseList %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for cr in courseList %}
        <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="course" value="{{cr}}">{{cr.code}}</button>
    {% endfor  %}
    </form>
    <p><h4><u>Course Name:</u> </h4> {{current_course.name}}</p>
    <p><h4><u>Course Code:</u> </h4> {{current_course.code}}</p>
	</ul>
	</div>
<h4><u>Deadlines:</u> </h4>
<table class="table table-striped">
  <thead>
    <tr>
    {% for dl in current_course.assignments_set.all %}
        <th>{{dl.name}}</th>
    {% endfor  %}
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for dl in current_course.assignments_set.all %}
        <td>{{dl.deadline}}</td>
    {% endfor  %}
    </tr>
  </tbody>
</table>
<h4><u>Feedbacks:</u> </h4>
<table class="table table-striped">
  <thead>
    <tr>
    {% for fb in current_course.feedbacks_set.all %}
        <form class="form-horizontal" action="{% url 'feedr:feedbacks' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="feedback" value="{{fb}}">{{fb.name}}</button>
        </form>
    {% endfor  %}
    </tr>
  </thead>
</table>
<h4><u>Students:</u> </h4>
<table class="table table-striped">
  <tbody>
    {% for st in current_course.students.all %}
    <tr>
        <td>{{st.name}}</td>
        <td>{{st.roll_number}}</td>
        {% for cr in st.courses_set.all %}
        <td>{{cr.name}}</td>
        {% endfor  %}
    </tr>
    {% endfor  %}
  </tbody>
</table>
{% endif %}
</div>
</body>
</html>

lab10/feedr/templates/feedr/feedback.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>

{% if courseList %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for cr in courseList %}
        <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-default" name="course" value="{{cr}}">{{cr.code}}</button>
    {% endfor  %}
    </form>
	</ul>
	</div>
    <p><h4><u>Feedback Name:</u> </h4>{{current_feedback.name}}</p>
    <p><h4><u>Feedback Deadline:</u> </h4>{{current_feedback.deadline}}</p>
    <h4><u>Questions:</u> </h4>
<table class="table table-striped">
  <tbody>
    {% for ques in current_feedback.questions_set.all %}
    <tr>
        <td>{{ques.question}}</td>
    </tr>
    {% endfor  %}
  </tbody>
</table>
{% endif %}
</div>
</body>
</html>

lab10/feedr/templates/feedr/home.html
<!DOCTYPE html>
<html>
<head>
	<title>home</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>

{% include path|add:"/templates/feedr/navbar.html" %}
<h4>Welcome {{user.username}}</h4>
<br>
<br>
{% if user.username == "admin" %}
	<h5>Click <a href="/feedr/enroll">here</a> to register the students to database from csv file</h5>
{% endif %}
{% if courseList %}
<p>These are the available courses</p>
	<div id="nav">
	<ul class="nav nav-pills navbar" >
    {% for course in courseList %}
    <form class="form-horizontal" action="{% url 'feedr:courses' %}" method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-default" name="course" value="{{course}}">{{course.code}}</button>
    {% endfor  %}
	</ul>
	</div>
{% endif %}
</div>
</body>
</html>

lab10/feedr/templates/feedr/login.html
<!DOCTYPE html>
<html>
<head>
	<title>login</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>
<div class="row">
	<div class="col-xd-8"></div>
	<div class="navbar-right" style="margin-right: 17px">
    <a href="{% url 'feedr:signup' %}">SignUp</a> 
	</div>
	</div> 
	<br>
	<br>
	<br>
	<br>
	<div>
  <form class="form-horizontal" action="." method="post">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="email">Username:</label>
      <div class="col-sm-6">
        <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="pwd">Password:</label>
      <div class="col-sm-6">
        <input type="password" class="form-control" id="pwd" name="pwd" placeholder="Enter password">
      </div>
    </div>
        <div class="form-group">
      <div class="col-sm-offset-6 col-sm-10" style="margin-bottom: 10px">
        <button type="submit" class="btn btn-default">Login</button>
      </div>
      <div style="margin-left:630px">
        {% if error_message %}<p style="margin-top: 10px;color: red"><strong>{{ error_message }}</strong></p>{% endif %}
      </div>
    </div>

    </form>
	</div>
	</div>

</body>
</html>

lab10/feedr/templates/feedr/navbar.html
{% if user.username == "admin" %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
	<li class="{{activeStatus.0}}"><a href="/feedr/home">Home</a></li>
	<li class="{{activeStatus.1}}"><a href="/feedr/admin/add">Add Courses</a></li>	
	<li class="{{activeStatus.2}}"><a href="/feedr/admin/manage" >Manage courses</a></li>
	<li class="navbar-right" style="margin-right: 2px"><a href="/feedr/logout/" >Logout </a></li>
	</ul>
	</div>
{% else %}
	<div id="nav">
	<ul class="nav nav-pills navbar" >
	<li class="{{activeStatus.0}}"><a href="/feedr/home">Home</a></li>
	<li class="{{activeStatus.1}}"><a href="">Add Feedback</a></li>	
	<li class="{{activeStatus.2}}"><a href="/feedr/addDeadlines/" >Add Deadlines</a></li>
	<li class="{{activeStatus.3}}"><a href="" >View Feedback</a></li>
	<li class="{{activeStatus.4}}"><a href="/feedr/viewDeadlines" >View Deadlines</a></li>
	<li class="navbar-right" style="margin-right: 2px"><a href="/feedr/logout/" >Logout </a></li>
	</ul>
	</div>
{% endif %}

lab10/feedr/templates/feedr/signup.html
<!DOCTYPE html>
<html>
<head>
	<title>signup</title>
	<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="utf-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate, post-check=0, pre-check=0" /> 
    <meta http-equiv="Pragma" content="no-cache" />
</head>
<body>
	<div class="container-fluid">
	<h2>FEEDER22</h2>
	<hr>
	
 {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
 {% endif %}
 <br>
  <br>
   <br>
    <br>
	<div>
  <form class="form-horizontal" action="." method="post">
  {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_email">Email-Id:</label>
      <div class="col-sm-6">
        <input class="form-control" id="id_email" name="email" type="email" required />
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_username">Username:</label>
      <div class="col-sm-6">
        <input class="form-control" id="id_username" name="username" type="text" required />
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_password">Password:</label>
      <div class="col-sm-6">
        <input class="form-control" id="id_password" minlength="4" name="password" type="password" required />
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-4" for="id_pwd2">Confirm Password:</label>
      <div class="col-sm-6">
        <input class="form-control" id="id_pwd2" minlength="4" name="pwd2" type="password" required />
      </div>
    </div>
        <div class="form-group">
      <div class="col-sm-offset-6 col-sm-10">
        <button type="submit" class="btn btn-default" >Register</button>
      </div>
   
    </div>

    </form>
	</div>
	</div>
	<script src="check.js"></script>
</body>
</html>